begin;
select plan(40);
select has_table('public','configuracion_centro','Existe configuración del centro');
select has_table('public','profesionales','Existe catálogo de profesionales');
select has_table('public','configuracion_alertas','Existe configuración de alertas');
select is((select relrowsecurity from pg_class where oid='public.configuracion_centro'::regclass),true,'Centro usa RLS');
select is((select relrowsecurity from pg_class where oid='public.profesionales'::regclass),true,'Profesionales usa RLS');
select is((select relrowsecurity from pg_class where oid='public.configuracion_alertas'::regclass),true,'Alertas usa RLS');
select is((select count(*)::int from public.configuracion_centro),1,'Centro es singleton');
select is((select count(*)::int from public.configuracion_alertas),1,'Alertas es singleton');
select ok(not has_table_privilege('anon','public.configuracion_centro','SELECT'),'Anon no lee centro');
select ok(not has_table_privilege('anon','public.profesionales','SELECT'),'Anon no lee profesionales');
select ok(not has_table_privilege('anon','public.configuracion_alertas','SELECT'),'Anon no lee alertas');
select ok(not exists(select 1 from pg_class c cross join lateral aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) a where c.oid='public.configuracion_centro'::regclass and a.grantee=0 and a.privilege_type='SELECT'),'PUBLIC no lee centro');
select ok(not exists(select 1 from pg_class c cross join lateral aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) a where c.oid='public.profesionales'::regclass and a.grantee=0 and a.privilege_type='SELECT'),'PUBLIC no lee profesionales');
select ok(not exists(select 1 from pg_class c cross join lateral aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) a where c.oid='public.configuracion_alertas'::regclass and a.grantee=0 and a.privilege_type='SELECT'),'PUBLIC no lee alertas');
select ok(not has_table_privilege('authenticated','public.configuracion_centro','DELETE'),'Authenticated no borra centro');
select ok(not has_table_privilege('authenticated','public.profesionales','DELETE'),'Authenticated no borra profesionales');
select ok(not has_table_privilege('authenticated','public.configuracion_alertas','DELETE'),'Authenticated no borra configuración de alertas');
select ok(not has_table_privilege('authenticated','public.configuracion_centro','INSERT'),'No se puede crear un segundo centro');
select ok(not has_table_privilege('authenticated','public.configuracion_alertas','INSERT'),'No se puede crear una segunda configuración de alertas');
select ok(not has_column_privilege('authenticated','public.configuracion_centro','id','UPDATE'),'No se puede alterar la identidad del centro');
select ok(not has_column_privilege('authenticated','public.configuracion_centro','created_at','UPDATE'),'No se puede alterar la creación del centro');
select ok(not has_column_privilege('authenticated','public.profesionales','id','INSERT'),'No se puede elegir la identidad de un profesional');
select ok(not has_column_privilege('authenticated','public.configuracion_alertas','updated_at','UPDATE'),'updated_at sólo se modifica mediante trigger');
select policies_are('public','configuracion_centro',array['configuracion_centro_admin_update','configuracion_centro_read'],'Centro sólo tiene las políticas previstas');
select policies_are('public','profesionales',array['profesionales_admin_insert','profesionales_admin_update','profesionales_read'],'Profesionales sólo tiene las políticas previstas');
select policies_are('public','configuracion_alertas',array['configuracion_alertas_admin_update','configuracion_alertas_read'],'Alertas sólo tiene las políticas previstas');
select has_trigger('public','configuracion_centro','club_del_kine_updated_configuracion_centro','Centro actualiza updated_at');
select has_trigger('public','configuracion_centro','club_del_kine_audit_configuracion_centro','Centro se audita');
select has_trigger('public','profesionales','club_del_kine_updated_profesionales','Profesionales actualiza updated_at');
select has_trigger('public','profesionales','club_del_kine_audit_profesionales','Profesionales se audita');
select has_trigger('public','configuracion_alertas','club_del_kine_updated_configuracion_alertas','Alertas actualiza updated_at');
select has_trigger('public','configuracion_alertas','club_del_kine_audit_configuracion_alertas','Alertas se audita');
select has_function('public','sincronizar_alertas_operativas',array[]::text[],'La sincronización sigue disponible');
select ok((select prosecdef from pg_proc where oid='public.sincronizar_alertas_operativas()'::regprocedure),'La sincronización es SECURITY DEFINER');
select ok((select exists(select 1 from unnest(proconfig) setting where replace(setting,' ','')='search_path=pg_catalog,pg_temp') from pg_proc where oid='public.sincronizar_alertas_operativas()'::regprocedure),'La sincronización fija un search_path seguro');
select ok(has_function_privilege('authenticated','public.sincronizar_alertas_operativas()','EXECUTE'),'Authenticated puede invocar la sincronización sujeta al control interno de rol');
select ok(not has_function_privilege('anon','public.sincronizar_alertas_operativas()','EXECUTE'),'Anon no puede ejecutar la sincronización');
select ok(not exists(select 1 from pg_proc p cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where p.oid='public.sincronizar_alertas_operativas()'::regprocedure and a.grantee=0 and a.privilege_type='EXECUTE'),'PUBLIC no puede ejecutar la sincronización');
select ok(not exists(select 1 from pg_policy where polrelid in ('public.configuracion_centro'::regclass,'public.profesionales'::regclass,'public.configuracion_alertas'::regclass) and (coalesce(pg_get_expr(polqual,polrelid),'')||coalesce(pg_get_expr(polwithcheck,polrelid),'')) ilike '%desarrollador%'),'Las políticas no conceden acceso al rol desarrollador');
select ok(not has_table_privilege('authenticated','public.licencias','UPDATE'),'Configuración no habilita cambios de licencia');
select * from finish();
rollback;
