import { friendlyDatabaseError } from './errorMessage'
import { supabase } from './supabase'
import type { AlertView, WaitingView } from '../types/stage9'
function client(){if(!supabase)throw new Error('Supabase no está configurado.');return supabase}

export async function syncAlerts(){const{data,error}=await client().rpc('sincronizar_alertas_operativas');if(error)throw new Error(friendlyDatabaseError(error));return data}
export async function alertCount(){const{count,error}=await client().from('alertas').select('id',{count:'exact',head:true}).eq('estado','pendiente');if(error)throw new Error(friendlyDatabaseError(error));return count??0}
export async function listAlerts(){const result=await client().from('alertas').select('*').in('estado',['pendiente','vista']).order('severidad',{ascending:false}).order('created_at',{ascending:false}).limit(200);if(result.error)throw new Error(friendlyDatabaseError(result.error));const rows=result.data??[],ids=[...new Set(rows.map(item=>item.paciente_id).filter((id):id is string=>Boolean(id)))],patients=ids.length?await client().from('pacientes').select('id,nombres,apellidos,telefono').in('id',ids):{data:[],error:null};if(patients.error)throw new Error(friendlyDatabaseError(patients.error));const map=new Map((patients.data??[]).map(item=>[item.id,item]));return rows.map(item=>({...item,paciente:item.paciente_id?map.get(item.paciente_id)??null:null})) as AlertView[]}
export async function changeAlertState(id:string,state:'vista'|'resuelta'|'descartada'){const{error}=await client().rpc('cambiar_estado_alerta',{p_alerta_id:id,p_estado:state});if(error)throw new Error(friendlyDatabaseError(error))}

export async function waitingCatalogs(){const[patients,treatments,types,boxes]=await Promise.all([client().from('pacientes').select('id,nombres,apellidos,dni,telefono').eq('estado','activo').order('apellidos').limit(5000),client().from('tratamientos').select('id,paciente_id,tipo_tratamiento_id').eq('estado','activo'),client().from('tipos_tratamiento').select('id,nombre').eq('activo',true),client().from('boxes').select('id,nombre').eq('activo',true)]);const error=patients.error??treatments.error??types.error??boxes.error;if(error)throw new Error(friendlyDatabaseError(error));return{patients:patients.data??[],treatments:treatments.data??[],types:types.data??[],boxes:boxes.data??[]}}
export async function listWaiting(){const[result,catalogs]=await Promise.all([client().from('lista_espera').select('*').order('prioridad').order('created_at'),waitingCatalogs()]);if(result.error)throw new Error(friendlyDatabaseError(result.error));const patients=new Map(catalogs.patients.map(i=>[i.id,i])),types=new Map(catalogs.types.map(i=>[i.id,i.nombre])),boxes=new Map(catalogs.boxes.map(i=>[i.id,i.nombre])),treatments=new Map(catalogs.treatments.map(i=>[i.id,i]));return(result.data??[]).map(item=>{const treatment=item.tratamiento_id?treatments.get(item.tratamiento_id):null;return{...item,paciente:patients.get(item.paciente_id)??null,tratamiento_nombre:treatment?types.get(treatment.tipo_tratamiento_id)??'Tratamiento':item.tipo_tratamiento_id?types.get(item.tipo_tratamiento_id)??'Tratamiento':null,box_nombre:item.box_id?boxes.get(item.box_id)??null:null}}) as WaitingView[]}
export async function createWaiting(values:{paciente_id:string;tratamiento_id:string|null;tipo_tratamiento_id:string|null;box_id:string|null;fecha_desde:string;fecha_hasta:string|null;hora_desde:string|null;hora_hasta:string|null;dias_semana:number[];prioridad:number;observaciones:string|null}){const{error}=await client().from('lista_espera').insert({...values,estado:'activa'});if(error)throw new Error(friendlyDatabaseError(error))}
export async function setWaitingState(id:string,state:string){const{error}=await client().from('lista_espera').update({estado:state}).eq('id',id);if(error)throw new Error(friendlyDatabaseError(error))}
