import { ArrowLeft, Box, Clock3, Pencil, Plus, Users } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { toast } from 'sonner'
import { Badge } from '../../components/ui/Badge'
import { Modal } from '../../components/ui/Modal'
import { listBoxesWithSchedules } from '../../services/turnos.service'
import type { BoxRow, ScheduleRow } from '../../types/stage5'
import { BoxForm } from './BoxForm'

export function BoxesPage(){const[boxes,setBoxes]=useState<BoxRow[]>([]),[schedules,setSchedules]=useState<ScheduleRow[]>([]),[editing,setEditing]=useState<BoxRow|null|'new'>(null),[loading,setLoading]=useState(true);const load=useCallback(async()=>{setLoading(true);try{const result=await listBoxesWithSchedules();setBoxes(result.boxes);setSchedules(result.schedules)}catch(error){toast.error(error instanceof Error?error.message:'No se pudieron cargar los boxes.')}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);return <><Link className="back-link" to="/turnos"><ArrowLeft size={17}/> Volver al calendario</Link><header className="page-heading module-heading"><div><p>Configuración de capacidad</p><h1>Boxes</h1><span>Espacios, cupos y horarios habituales</span></div><button className="primary-button" onClick={()=>setEditing('new')}><Plus size={18}/> Nuevo box</button></header>{loading?<div className="table-loading">Cargando boxes…</div>:<div className="box-grid">{boxes.map((box)=>{const own=schedules.filter((item)=>item.box_id===box.id),morning=own.sort((a,b)=>a.hora_desde.localeCompare(b.hora_desde))[0],afternoon=own.sort((a,b)=>b.hora_desde.localeCompare(a.hora_desde))[0];return <article className="box-card" key={box.id}><header><span><Box size={22}/></span><Badge tone={box.activo?'green':'gray'}>{box.activo?'Activo':'Inactivo'}</Badge></header><h2>{box.nombre}</h2><p>{box.descripcion||'Sin descripción'}</p><dl><div><dt><Users size={14}/> Capacidad</dt><dd>{box.capacidad} paciente{box.capacidad>1?'s':''} simultáneo{box.capacidad>1?'s':''}</dd></div><div><dt><Clock3 size={14}/> Mañana</dt><dd>{morning?`${morning.hora_desde.slice(0,5)} a ${morning.hora_hasta.slice(0,5)}`:'Sin configurar'}</dd></div><div><dt><Clock3 size={14}/> Tarde</dt><dd>{afternoon?`${afternoon.hora_desde.slice(0,5)} a ${afternoon.hora_hasta.slice(0,5)}`:'Sin configurar'}</dd></div></dl><footer><button onClick={()=>setEditing(box)}><Pencil size={15}/> Editar configuración</button></footer></article>})}</div>}<Modal open={editing!==null} title={editing==='new'?'Nuevo box':'Configurar box'} onClose={()=>setEditing(null)}><BoxForm box={editing==='new'?null:editing} schedules={schedules} onCancel={()=>setEditing(null)} onSuccess={()=>{setEditing(null);void load()}}/></Modal></>}
