import { useEffect, useState, type FormEvent } from 'react'
import { toast } from 'sonner'
import { saveBox } from '../../services/turnos.service'
import type { BoxFormData, BoxRow, ScheduleRow } from '../../types/stage5'

const days=['Dom','Lun','Mar','Mié','Jue','Vie','Sáb']
export function BoxForm({box,schedules,onSuccess,onCancel}:{box?:BoxRow|null;schedules:ScheduleRow[];onSuccess:()=>void;onCancel:()=>void}){
 const own=schedules.filter((item)=>item.box_id===box?.id),morning=own.sort((a,b)=>a.hora_desde.localeCompare(b.hora_desde))[0],afternoon=own.sort((a,b)=>b.hora_desde.localeCompare(a.hora_desde))[0]
 const [values,setValues]=useState<BoxFormData>({nombre:'',descripcion:null,capacidad:1,activo:true,dias:[1,2,3,4,5],manana_desde:'08:00',manana_hasta:'12:00',tarde_desde:'14:00',tarde_hasta:'20:00'}),[saving,setSaving]=useState(false)
 useEffect(()=>{setValues({nombre:box?.nombre??'',descripcion:box?.descripcion??null,capacidad:box?.capacidad??1,activo:box?.activo??true,dias:own.length?[...new Set(own.map((item)=>item.dia_semana))]:[1,2,3,4,5],manana_desde:morning?.hora_desde.slice(0,5)??'08:00',manana_hasta:morning?.hora_hasta.slice(0,5)??'12:00',tarde_desde:afternoon?.hora_desde.slice(0,5)??'14:00',tarde_hasta:afternoon?.hora_hasta.slice(0,5)??'20:00'})},[box])
 const toggle=(day:number)=>setValues((current)=>({...current,dias:current.dias.includes(day)?current.dias.filter((item)=>item!==day):[...current.dias,day].sort()}))
 async function submit(event:FormEvent){event.preventDefault();if(!values.nombre.trim()||!values.dias.length)return toast.error('Indicá el nombre y al menos un día de atención.');if(values.manana_hasta<=values.manana_desde||values.tarde_hasta<=values.tarde_desde)return toast.error('Revisá los rangos horarios.');setSaving(true);try{await saveBox(box?.id??null,values);toast.success(box?'Box actualizado.':'Box creado.');onSuccess()}catch(error){toast.error(error instanceof Error?error.message:'No se pudo guardar.')}finally{setSaving(false)}}
 return <form className="entity-form" onSubmit={submit}><div className="form-section"><h3>Información del box</h3><div className="form-grid"><label><span>Nombre *</span><input value={values.nombre} onChange={(e)=>setValues({...values,nombre:e.target.value})} required/></label><label><span>Capacidad simultánea *</span><input type="number" min="1" max="10" value={values.capacidad} onChange={(e)=>setValues({...values,capacidad:Number(e.target.value)})}/></label><label className="full"><span>Función o descripción</span><textarea value={values.descripcion??''} onChange={(e)=>setValues({...values,descripcion:e.target.value||null})} placeholder="Rehabilitación, masoterapia, magnetoterapia…"/></label><label className="switch-label"><span>Estado</span><button type="button" className={`switch ${values.activo?'on':''}`} onClick={()=>setValues({...values,activo:!values.activo})}><i/>{values.activo?'Activo':'Inactivo'}</button></label></div></div><div className="form-section"><h3>Días y horarios habituales</h3><div className="weekday-picker">{days.map((label,index)=><button type="button" key={label} className={values.dias.includes(index)?'active':''} onClick={()=>toggle(index)}>{label}</button>)}</div><div className="form-grid"><label><span>Mañana desde</span><input type="time" value={values.manana_desde} onChange={(e)=>setValues({...values,manana_desde:e.target.value})}/></label><label><span>Mañana hasta</span><input type="time" value={values.manana_hasta} onChange={(e)=>setValues({...values,manana_hasta:e.target.value})}/></label><label><span>Tarde desde</span><input type="time" value={values.tarde_desde} onChange={(e)=>setValues({...values,tarde_desde:e.target.value})}/></label><label><span>Tarde hasta</span><input type="time" value={values.tarde_hasta} onChange={(e)=>setValues({...values,tarde_hasta:e.target.value})}/></label></div></div><footer className="form-actions"><button type="button" className="secondary-button" onClick={onCancel}>Cancelar</button><button className="primary-button" disabled={saving}>{saving?'Guardando…':'Guardar configuración'}</button></footer></form>
}
