import { useEffect, useState, type FormEvent } from 'react'
import { toast } from 'sonner'
import { listActiveTreatments } from '../../services/sesiones.service'
import { getStage4Catalogs } from '../../services/tratamientos.service'
import { createTurno, updateTurno } from '../../services/turnos.service'
import type { Stage4Catalogs } from '../../types/stage4'
import type { TurnoFormData, TurnoView } from '../../types/stage5'

type TreatmentOption={id:string;paciente_id:string;diagnostico:string|null;tipo:{nombre:string}|null}
function argentinaParts(value:string){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Argentina/Buenos_Aires',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(value));const get=(type:string)=>parts.find((part)=>part.type===type)?.value??'';return{date:`${get('year')}-${get('month')}-${get('day')}`,time:`${get('hour')}:${get('minute')}`}}

export function TurnoForm({turno,initialDate,initialTime,initialBoxId,onSuccess,onCancel}:{turno?:TurnoView|null;initialDate:string;initialTime?:string;initialBoxId?:string;onSuccess:()=>void;onCancel:()=>void}){
 const [catalogs,setCatalogs]=useState<Stage4Catalogs|null>(null),[treatments,setTreatments]=useState<TreatmentOption[]>([]),[saving,setSaving]=useState(false),[duration,setDuration]=useState(30)
 const existing=turno?argentinaParts(turno.inicio_at):null
 const [patientId,setPatientId]=useState(turno?.paciente_id??''),[treatmentId,setTreatmentId]=useState(turno?.tratamiento_id??''),[boxId,setBoxId]=useState(turno?.box_id??initialBoxId??''),[date,setDate]=useState(existing?.date??initialDate),[time,setTime]=useState(existing?.time??initialTime??'08:00'),[status,setStatus]=useState(turno?.estado??'programado'),[notes,setNotes]=useState(turno?.observaciones??'')
 useEffect(()=>{void getStage4Catalogs().then(setCatalogs).catch((error)=>toast.error(error.message))},[])
 useEffect(()=>{void listActiveTreatments(patientId||undefined).then((data)=>setTreatments(data as unknown as TreatmentOption[])).catch((error)=>toast.error(error.message))},[patientId])
 useEffect(()=>{if(!turno){setDate(initialDate);if(initialTime)setTime(initialTime);if(initialBoxId)setBoxId(initialBoxId)}},[initialDate,initialTime,initialBoxId,turno])
 async function submit(event:FormEvent){event.preventDefault();if(!patientId||!treatmentId||!boxId)return toast.error('Paciente, tratamiento y box son obligatorios.');const start=new Date(`${date}T${time}:00-03:00`),end=new Date(start.getTime()+duration*60000);const values:TurnoFormData={paciente_id:patientId,tratamiento_id:treatmentId,box_id:boxId,inicio_at:start.toISOString(),fin_at:end.toISOString(),estado:status as TurnoFormData['estado'],observaciones:notes.trim()||null};setSaving(true);try{if(turno)await updateTurno(turno.id,values);else await createTurno(values);toast.success(turno?'Turno actualizado.':'Turno reservado.');onSuccess()}catch(error){toast.error(error instanceof Error?error.message:'No se pudo guardar el turno.')}finally{setSaving(false)}}
 return <form className="entity-form" onSubmit={submit}><div className="form-section"><h3>Paciente y tratamiento</h3><div className="form-grid"><label className="full"><span>Paciente *</span><select value={patientId} disabled={Boolean(turno)} onChange={(e)=>{setPatientId(e.target.value);setTreatmentId('')}} required><option value="">Seleccionar paciente</option>{catalogs?.pacientes.map((item)=><option key={item.id} value={item.id}>{item.apellidos}, {item.nombres} · DNI {item.dni}</option>)}</select></label><label className="full"><span>Tratamiento activo *</span><select value={treatmentId} disabled={Boolean(turno)} onChange={(e)=>setTreatmentId(e.target.value)} required><option value="">Seleccionar tratamiento</option>{treatments.map((item)=><option key={item.id} value={item.id}>{item.tipo?.nombre??'Tratamiento'}{item.diagnostico?` · ${item.diagnostico}`:''}</option>)}</select></label></div></div><div className="form-section"><h3>Fecha, horario y box</h3><div className="form-grid three"><label><span>Fecha *</span><input type="date" value={date} onChange={(e)=>setDate(e.target.value)} required/></label><label><span>Hora *</span><input type="time" step="1800" value={time} onChange={(e)=>setTime(e.target.value)} required/></label><label><span>Duración</span><select value={duration} onChange={(e)=>setDuration(Number(e.target.value))}><option value="30">30 minutos</option><option value="45">45 minutos</option><option value="60">60 minutos</option><option value="90">90 minutos</option></select></label><label><span>Box *</span><select value={boxId} onChange={(e)=>setBoxId(e.target.value)} required><option value="">Seleccionar box</option>{catalogs?.boxes.map((item)=><option key={item.id} value={item.id}>{item.nombre}</option>)}</select></label><label><span>Estado</span><select value={status} onChange={(e)=>setStatus(e.target.value)}><option value="programado">Reservado</option><option value="confirmado">Confirmado</option><option value="presente">Llegó</option><option value="atendido">Atendido</option><option value="ausente">Ausente</option></select></label><label className="full"><span>Observaciones</span><textarea value={notes} onChange={(e)=>setNotes(e.target.value)}/></label></div></div><footer className="form-actions"><button type="button" className="secondary-button" onClick={onCancel}>Cancelar</button><button className="primary-button" disabled={saving}>{saving?'Guardando…':turno?'Guardar cambios':'Reservar turno'}</button></footer></form>
}
