import { CalendarDays, ChevronLeft, ChevronRight, Clock3, Plus, Settings2, Users } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { toast } from 'sonner'
import { Badge, type BadgeTone } from '../../components/ui/Badge'
import { Modal } from '../../components/ui/Modal'
import { getCalendarData, setTurnoEstado } from '../../services/turnos.service'
import type { CalendarData, TurnoView } from '../../types/stage5'
import { TurnoForm } from './TurnoForm'

type View='dia'|'semana'|'mes'
const labels:Record<string,string>={programado:'Reservado',confirmado:'Confirmado',presente:'Llegó',atendido:'Atendido',ausente:'Ausente',cancelado:'Cancelado'}
const tones:Record<string,BadgeTone>={programado:'blue',confirmado:'amber',presente:'green',atendido:'green',ausente:'red',cancelado:'gray'}
const isoDate=(date:Date)=>{const local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,10)}
const addDays=(date:Date,days:number)=>{const next=new Date(date);next.setDate(next.getDate()+days);return next}
const slots=Array.from({length:25},(_,index)=>{const minutes=8*60+index*30;return`${String(Math.floor(minutes/60)).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')}`})

export function TurnosPage(){
 const [date,setDate]=useState(()=>new Date()),[view,setView]=useState<View>('dia'),[data,setData]=useState<CalendarData>({turnos:[],boxes:[],schedules:[]}),[loading,setLoading]=useState(true),[editing,setEditing]=useState<TurnoView|null|'new'>(null),[slot,setSlot]=useState<{time?:string;boxId?:string}>({})
 const range=useMemo(()=>{if(view==='dia')return{from:new Date(`${isoDate(date)}T00:00:00-03:00`),to:new Date(`${isoDate(addDays(date,1))}T00:00:00-03:00`)};if(view==='semana'){const start=addDays(date,-((date.getDay()+6)%7));return{from:new Date(`${isoDate(start)}T00:00:00-03:00`),to:new Date(`${isoDate(addDays(start,7))}T00:00:00-03:00`)}}const start=new Date(date.getFullYear(),date.getMonth(),1);return{from:new Date(`${isoDate(start)}T00:00:00-03:00`),to:new Date(`${isoDate(new Date(date.getFullYear(),date.getMonth()+1,1))}T00:00:00-03:00`)}},[date,view])
 const load=useCallback(async()=>{setLoading(true);try{setData(await getCalendarData(range.from.toISOString(),range.to.toISOString()))}catch(error){toast.error(error instanceof Error?error.message:'No se pudo cargar la agenda.')}finally{setLoading(false)}},[range])
 useEffect(()=>{void load()},[load])
 const navigate=(direction:number)=>setDate((current)=>addDays(current,direction*(view==='dia'?1:view==='semana'?7:30)))
 const openNew=(time?:string,boxId?:string)=>{setSlot({time,boxId});setEditing('new')}
 async function state(row:TurnoView,status:string){let reason;if(status==='cancelado'){reason=window.prompt('Motivo de cancelación. El turno permanecerá en el historial:');if(!reason?.trim())return}try{await setTurnoEstado(row.id,status,reason);toast.success('Estado actualizado.');void load()}catch(error){toast.error(error instanceof Error?error.message:'No se pudo actualizar el turno.')}}
 const dayTitle=new Intl.DateTimeFormat('es-AR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(date)
 const dayTurns=data.turnos.filter((turn)=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Argentina/Buenos_Aires'}).format(new Date(turn.inicio_at))===isoDate(date))
 const slotTurns=(time:string,boxId:string)=>dayTurns.filter((turn)=>{const formatted=new Intl.DateTimeFormat('en-GB',{timeZone:'America/Argentina/Buenos_Aires',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(turn.inicio_at));return formatted===time&&turn.box_id===boxId&&turn.estado!=='cancelado'})
 return <><header className="page-heading module-heading"><div><p>Agenda del centro</p><h1>Turnos</h1><span>{dayTitle}</span></div><div className="heading-actions"><Link className="secondary-button" to="/boxes"><Settings2 size={17}/> Boxes y capacidad</Link><button className="primary-button" onClick={()=>openNew()}><Plus size={18}/> Nuevo turno</button></div></header><section className="calendar-toolbar"><div className="calendar-nav"><button onClick={()=>navigate(-1)} aria-label="Anterior"><ChevronLeft size={18}/></button><button onClick={()=>setDate(new Date())}>Hoy</button><button onClick={()=>navigate(1)} aria-label="Siguiente"><ChevronRight size={18}/></button></div><div className="view-switch">{(['dia','semana','mes'] as View[]).map((item)=><button key={item} className={view===item?'active':''} onClick={()=>setView(item)}>{item}</button>)}</div><input type="date" value={isoDate(date)} onChange={(e)=>setDate(new Date(`${e.target.value}T12:00:00`))}/></section>{loading?<div className="table-loading">Cargando calendario…</div>:view==='dia'?<section className="calendar-day"><div className="calendar-grid calendar-head"><span>Horario</span>{data.boxes.map((box)=><div key={box.id}><strong>{box.nombre}</strong><small>Capacidad {box.capacidad}</small></div>)}</div>{slots.map((time)=><div className="calendar-grid calendar-row" key={time}><time>{time}</time>{data.boxes.map((box)=>{const turns=slotTurns(time,box.id),available=Math.max(box.capacidad-turns.length,0);return <div className={`calendar-cell ${available?'available':'full'}`} key={box.id}>{turns.map((turn)=><button className="appointment-chip" key={turn.id} onClick={()=>setEditing(turn)}><strong>{turn.paciente?.apellidos}, {turn.paciente?.nombres}</strong><small>{turn.tratamiento?.tipo_nombre} · {turn.obra_social_nombre??'Particular'}</small><Badge tone={tones[turn.estado]??'gray'}>{labels[turn.estado]??turn.estado}</Badge></button>)}{available>0&&<button className="free-slot" onClick={()=>openNew(time,box.id)}><Plus size={14}/><span>Disponible{box.capacidad>1?` · ${available} cupo${available>1?'s':''}`:''}</span></button>}</div>})}</div>)}</section>:<CalendarSummary view={view} date={date} turns={data.turnos} boxes={data.boxes}/>}<Modal open={editing!==null} title={editing==='new'?'Nuevo turno':'Detalle del turno'} onClose={()=>setEditing(null)} wide>{editing!=='new'&&editing?<div className="appointment-actions"><button onClick={()=>void state(editing,'presente')}><Users size={16}/> Marcar llegada</button><button onClick={()=>void state(editing,'atendido')}><Clock3 size={16}/> Marcar atendido</button><button className="danger" onClick={()=>void state(editing,'cancelado')}>Cancelar turno</button></div>:null}<TurnoForm turno={editing==='new'?null:editing} initialDate={isoDate(date)} initialTime={slot.time} initialBoxId={slot.boxId} onCancel={()=>setEditing(null)} onSuccess={()=>{setEditing(null);void load()}}/></Modal></>
}

function CalendarSummary({view,date,turns,boxes}:{view:View;date:Date;turns:TurnoView[];boxes:CalendarData['boxes']}){const start=view==='semana'?addDays(date,-((date.getDay()+6)%7)):new Date(date.getFullYear(),date.getMonth(),1);const count=view==='semana'?7:new Date(date.getFullYear(),date.getMonth()+1,0).getDate();return <section className={`calendar-summary ${view}`}>{Array.from({length:count},(_,index)=>{const day=addDays(start,index),key=isoDate(day),daily=turns.filter((turn)=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Argentina/Buenos_Aires'}).format(new Date(turn.inicio_at))===key&&turn.estado!=='cancelado'),capacity=Math.max(boxes.reduce((sum,box)=>sum+box.capacidad,0)*25,1),ratio=daily.length/capacity,status=ratio>=1?'Completo':ratio>.75?'Casi completo':ratio>.4?'Disponibilidad media':'Disponibilidad alta';return <article key={key} className={ratio>=1?'full':ratio>.75?'almost':ratio>.4?'medium':'high'}><span>{new Intl.DateTimeFormat('es-AR',{weekday:'short'}).format(day)}</span><strong>{day.getDate()}</strong><small>{daily.length} turnos</small><em>{status}</em></article>})}</section>}
