import { BellRing,Check,Eye,MessageCircle,RefreshCcw,X } from 'lucide-react'
import { useCallback,useEffect,useState } from 'react'
import { toast } from 'sonner'
import { Badge,type BadgeTone } from '../../components/ui/Badge'
import { WhatsAppModal } from '../../components/WhatsAppModal'
import { changeAlertState,listAlerts,syncAlerts } from '../../services/operaciones.service'
import type { AlertView } from '../../types/stage9'
import { formatDateTime } from '../../utils/date'
const tones:Record<string,BadgeTone>={info:'blue',advertencia:'amber',critica:'red'}
export function AlertasPage(){const[rows,setRows]=useState<AlertView[]>([]),[loading,setLoading]=useState(true),[contact,setContact]=useState<AlertView|null>(null);const load=useCallback(async()=>{setLoading(true);try{await syncAlerts();setRows(await listAlerts())}catch(error){toast.error(error instanceof Error?error.message:'No se pudieron cargar las alertas.')}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);async function change(row:AlertView,state:'vista'|'resuelta'|'descartada'){try{await changeAlertState(row.id,state);toast.success(state==='resuelta'?'Alerta resuelta.':'Alerta actualizada.');void load()}catch(error){toast.error(error instanceof Error?error.message:'No se pudo actualizar.')}}return <><header className="page-heading module-heading"><div><p>Seguimiento operativo</p><h1>Alertas</h1><span>Situaciones que requieren atención de recepción</span></div><button className="secondary-button" onClick={()=>void load()}><RefreshCcw size={17}/> Actualizar alertas</button></header><section className="panel entity-panel">{loading?<div className="table-loading">Revisando alertas.</div>:rows.length?<div className="alert-list">{rows.map(row=><article key={row.id} className={`alert-card ${row.severidad}`}><span className="alert-symbol"><BellRing size={19}/></span><div><header><Badge tone={tones[row.severidad]??'gray'}>{row.severidad}</Badge><small>{formatDateTime(row.created_at)}</small></header><h2>{row.titulo}</h2><p>{row.mensaje}</p>{row.paciente&&<strong>{row.paciente.apellidos}, {row.paciente.nombres}</strong>}</div><div className="alert-actions">{row.paciente?.telefono&&<button title="WhatsApp" onClick={()=>setContact(row)}><MessageCircle size={16}/></button>}<button title="Marcar vista" onClick={()=>void change(row,'vista')}><Eye size={16}/></button><button title="Resolver" onClick={()=>void change(row,'resuelta')}><Check size={16}/></button><button title="Descartar" onClick={()=>void change(row,'descartada')}><X size={16}/></button></div></article>)}</div>:<div className="empty-state"><Check size={30}/><strong>Todo al día</strong><p>No hay alertas operativas pendientes.</p></div>}</section>{contact?.paciente&&<WhatsAppModal open name={`${contact.paciente.nombres}`} phone={contact.paciente.telefono} initial={contact.tipo==='documentacion_pendiente'?'documentacion':contact.tipo==='lista_espera'?'disponible':'recordatorio'} onClose={()=>setContact(null)}/>}</>}
