import { Ban, CalendarClock, Check, ClipboardCheck, Pencil, Plus } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { toast } from 'sonner'
import { Badge, type BadgeTone } from '../../components/ui/Badge'
import { EmptyState } from '../../components/ui/EmptyState'
import { Modal } from '../../components/ui/Modal'
import { Pagination } from '../../components/ui/Pagination'
import { anularSesion, listSesiones } from '../../services/sesiones.service'
import type { SesionView } from '../../types/stage4'
import { formatDateTime } from '../../utils/date'
import { SesionForm } from './SesionForm'

const labels: Record<string,string> = { programada:'Programada', realizada:'Asistió', ausente_avisado:'Ausente avisado', ausente_consumida:'Ausente sin aviso', cancelada:'Cancelada', reprogramada:'Reprogramada', anulada:'Anulada' }
const tones: Record<string,BadgeTone> = { realizada:'green', programada:'blue', ausente_avisado:'amber', ausente_consumida:'red', cancelada:'gray', reprogramada:'blue', anulada:'red' }

export function SesionesPage({ pacienteId, tratamientoId, embedded = false }: { pacienteId?: string; tratamientoId?: string; embedded?: boolean }) {
  const [rows,setRows]=useState<SesionView[]>([]), [page,setPage]=useState(1), [total,setTotal]=useState(0), [pageSize,setPageSize]=useState(12)
  const [loading,setLoading]=useState(true), [editing,setEditing]=useState<SesionView | null | 'new'>(null)
  const load=useCallback(async()=>{setLoading(true);try{const result=await listSesiones(page,pacienteId,tratamientoId);setRows(result.data);setTotal(result.count);setPageSize(result.pageSize)}catch(error){toast.error(error instanceof Error?error.message:'No se pudieron cargar las sesiones.')}finally{setLoading(false)}},[page,pacienteId,tratamientoId])
  useEffect(()=>{void load()},[load])
  async function annul(row:SesionView){const reason=window.prompt('Motivo de anulación. La sesión seguirá visible en el historial:');if(!reason?.trim())return;try{await anularSesion(row.id,reason);toast.success('Sesión anulada sin eliminar el historial.');void load()}catch(error){toast.error(error instanceof Error?error.message:'No se pudo anular.')}}
  return <>{!embedded&&<header className="page-heading module-heading"><div><p>Seguimiento asistencial</p><h1>Sesiones</h1><span>Asistencias, ausencias y consumo autorizado</span></div><button className="primary-button" onClick={()=>setEditing('new')}><Check size={18}/> Registrar llegada</button></header>}{embedded&&<div className="embedded-heading"><div><h2>Historial de sesiones</h2><p>Las sesiones nunca se eliminan y el consumo se calcula con las reglas vigentes.</p></div><button className="primary-button compact" onClick={()=>setEditing('new')}><Plus size={17}/> Registrar sesión</button></div>}<section className="panel entity-panel"><div className="entity-toolbar"><span className="toolbar-note">{total} sesión{total===1?'':'es'} en el historial</span><span className="toolbar-note">Zona horaria: Argentina</span></div>{loading?<div className="table-loading">Cargando sesiones…</div>:rows.length?<div className="data-table-wrap"><table className="data-table session-table"><thead><tr><th>#</th><th>Paciente / tratamiento</th><th>Fecha y hora</th><th>Box</th><th>Estado</th><th>Consumo</th><th>Pago</th><th>Acciones</th></tr></thead><tbody>{rows.map((row,index)=><tr key={row.id}><td><strong>{total-((page-1)*pageSize+index)}</strong></td><td><div className="treatment-name"><ClipboardCheck size={16}/><span><strong>{row.paciente?.apellidos}, {row.paciente?.nombres}</strong><small>{row.tratamiento?.tipo?.nombre??'Tratamiento'}</small>{row.notas&&<em>{row.notas}</em>}</span></div></td><td>{formatDateTime(row.fecha_atencion)}</td><td>{row.box?.nombre??'—'}</td><td><Badge tone={tones[row.estado]??'gray'}>{labels[row.estado]??row.estado}</Badge></td><td><strong>{Number(row.unidades_consumidas).toLocaleString('es-AR')} sesión</strong></td><td><Badge tone={row.pago_aplicaciones.some((item)=>item.estado==='aplicado')?'green':'amber'}>{row.pago_aplicaciones.some((item)=>item.estado==='aplicado')?'Aplicado':'Pendiente'}</Badge></td><td><div className="row-actions"><button title="Editar" disabled={row.estado==='anulada'} onClick={()=>setEditing(row)}><Pencil size={15}/></button><button title="Anular" disabled={row.estado==='anulada'} onClick={()=>void annul(row)}><Ban size={15}/></button></div></td></tr>)}</tbody></table></div>:<EmptyState icon={CalendarClock} title="Sin sesiones registradas" description="Registrá la primera asistencia o ausencia del tratamiento."/>}{total>pageSize&&<Pagination page={page} pageSize={pageSize} total={total} onChange={setPage}/>}</section><Modal open={editing!==null} title={editing==='new'?'Registrar sesión':'Editar sesión'} onClose={()=>setEditing(null)} wide><SesionForm sesion={editing==='new'?null:editing} pacienteId={pacienteId} tratamientoId={tratamientoId} onCancel={()=>setEditing(null)} onSuccess={()=>{setEditing(null);void load()}}/></Modal></>
}
